// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI local (introspection / migrations / studio) : connexion DIRECTE
    // (5432, sans pgbouncer) — le pooler transactionnel casse l'introspection.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
